# Generated by Django 5.1.2 on 2024-11-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='session',
        ),
        migrations.AddField(
            model_name='rating',
            name='experience',
            field=models.CharField(choices=[('RETREAT', 'Retreat'), ('MEDITATION', 'Meditation'), ('HATHA CLASS', 'Hatha Class'), ('ASHTANGA CLASS', 'Ashtanga Class')], default='RETREAT', max_length=200),
        ),
    ]
