# Generated by Django 5.1.2 on 2024-11-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_rating_created_on_remove_rating_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
